plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
show_downloads: false

title: "Service de consultation en IA et données (SCIAD)"
description: "Service de consultation en intelligence artificielle et données offert par l'Institut intelligence et données de l'Université Laval. Note : le service est offert uniquement à la communauté IID pour le moment."
