plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
show_downloads: false

title: "[MIIA]"
description: "Informations sur la Maitrise professionnelle en Informatique Intelligence Artificielle (MIIA). Comment proposer un stage et avoir un financement, comment voir les stages disponibles, toutes les informations sur les différents processus de stage."
